### ISSUE TITLE
打包出错WARNING: signing is required for mas builds. Provide the osx-sign option, or manually sign the app later.

### ISSUE THREAD

**Issue by fantingsheng** [lanten/electron-antd#20]
执行npm run pack:mac 
打包出错WARNING: signing is required for mas builds. Provide the osx-sign option, or manually sign the app later.

**Comment by fantingsheng** [comment]
补充贴图<img width="747" alt="WX20191130-230524@2x" src="https://user-images.githubusercontent.com/6924543/69902290-bc30f980-13c6-11ea-8eda-0e4c9b472f8c.png">

**Comment by lanten** [comment]
您好，这是一个 mac 应用需要签名的警告，并不会影响打包，请检查 `prod` 目录。

**Comment by fantingsheng** [comment]
> 您好，这是一个 mac 应用需要签名的警告，并不会影响打包，请检查 `prod` 目录。

看到了，app文件已经生成了，感谢
