### ISSUE TITLE
Electron failed to install correctly

### ISSUE THREAD

**Issue by HiZhaoYun** [lanten/electron-antd#22]
最新的7版本国内安装好像都会失败，请问你是怎么解决的？

**Comment by lanten** [comment]
解决方案是使用淘宝镜像

编辑用户目录下的 `.npmrc ` 文件

```
code ~/.npmrc
```

添加下面代码：
```
electron_mirror="https://npm.taobao.org/mirrors/electron/"
electron_custom_dir="7.1.7"
```

保存后，删除项目中的 `node_modules` 尝试重新安装

**Comment by HiZhaoYun** [comment]
> 解决方案是使用淘宝镜像
> 
> 编辑用户目录下的 `.npmrc ` 文件
> 
> ```
> code ~/.npmrc
> ```
> 
> 添加下面代码：
> 
> ```
> electron_mirror="https://npm.taobao.org/mirrors/electron/"
> electron_custom_dir="7.1.7"
> ```
> 
> 保存后，删除项目中的 `node_modules` 尝试重新安装

It is work! 不过还是遇到一点问题，是因为缓存的问题，yarn cache 清掉就可以了。
