### ISSUE TITLE
请问Redux的异步数据流该怎么写

### ISSUE THREAD

**Issue by westmelon** [lanten/electron-antd#32]
我在xx.action.ts中写了一个异步action,但是这个异步action没有触发，请问该如何处理？

**Comment by lanten** [comment]
设计是 action 内部不存在异步操作，可以在 dispatch 的时候传入一个异步函数，此函数接收一个同步dispatch函数行参。
详细参考：https://github.com/lanten/electron-antd/blob/e189e807bf0992383fee8e1b6a8249f73509a677/app/src/views/demo/demo.tsx#L116-L126

**Comment by lanten** [comment]
调用： https://github.com/lanten/electron-antd/blob/e189e807bf0992383fee8e1b6a8249f73509a677/app/src/views/demo/demo.tsx#L77

**Comment by westmelon** [comment]
理解了，非常感谢
