### ISSUE TITLE
下载了怎么使用呀求求

### ISSUE THREAD

**Issue by l9821** [lanten/electron-antd#36]

**Comment by lanten** [comment]
这是一个开发模板，本身没有实质功能。

需要本地安装 nodejs 环境，进入项目目录执行 `npm install & npm run dev` 即可

**Comment by JIACHENG135** [comment]
可以来了解下用这个模版开发的项目,一个读书app和视频播放器? 另膜作者大大!
[LibGen - Desktop website 开发中](https://lib-gen.me)
[LibGen - Github下载试用](https://github.com/JIACHENG135/Electron-React-Book-Searcher/releases)
[JCPlayer](https://github.com/JIACHENG135/JCPlayer)
