### ISSUE TITLE
有计划升级到webpack5不呢

### ISSUE THREAD

**Issue by cooliean** [lanten/electron-antd#39]
大佬，现在感觉这样的项目编译真的慢，有计划升级到webpack5不呢，哈哈，我比较懒

**Comment by lanten** [comment]
你好，
Webpack 5 早就在做了，查看 [webpack-5](https://github.com/lanten/electron-antd/tree/webpack-5)分支，还有一些其他优化。

事实上，webpack 5 最大的改动是模块联邦（Module Federation），通常用于微前端架构，对于 Electron 应用提升不大，有大佬测试过，就编译速度而言，反而略慢于 Webpack 4。

**Comment by cooliean** [comment]
好像是啊，我昨天看了一下，好像确实没有什么编译速度上的提升
