### ISSUE TITLE
大佬，我在项目里面用了child_process来执行命令，发现打win包之后不起作用了，调试是可以的

### ISSUE THREAD

**Issue by Armyoftheworld** [lanten/electron-antd#4]
我的项目地址：https://gitee.com/Armyoftheworld/electron-antd
运行之后，点击打开jar这个标签，然后项目根目录下有个classes-dex2jar.jar文件，可以选择这个文件，点击执行，发现没反应，看我的打印里面是报错了
![qq 20190215181349](https://user-images.githubusercontent.com/10347401/52850053-867b9680-314d-11e9-97b4-b8478b8e5b30.png)

直接用npm start启动的话，没有这个错误，而且可以打开一个新窗口的。
请问您能帮我看看吗？

**Comment by Armyoftheworld** [comment]
openJar组件是文件是src\components\openJar\OpenJar.js这个
执行命令是这个文件src\utils\exec.js

**Comment by lanten** [comment]
您好，

不推荐在渲染进程中使用 node 模块（如 `child_process`），你应该在 [electron/api/electron.fn.js](https://github.com/lanten/electron-antd/blob/master/electron/api/electron.fn.js) 中添加一个方法，并在渲染进程中通过全局变量 `$api` 来调用它。

此外，`static` 文件夹默认被添加到了忽略列表中，打包时会被忽略，你可以自行移除，详情见：[config/package.config.js 第12行](https://github.com/lanten/electron-antd/blob/ae4a0d41e99ff014cdf17cab3584ae1cd7c9b71b/config/package.config.js#L12)

**Comment by Armyoftheworld** [comment]
解决了，是child_process执行命令的工作目录指定的有问题，不能用相对路径./static/tools
