### ISSUE TITLE
关于渲染性能，触发网络请求后渲染进程掉帧严重有办法解决吗？

### ISSUE THREAD

**Issue by Liu-Ya** [lanten/electron-antd#40]
切换分页后，掉帧到 1~2 FPS/s，是因为 $api.request 堵塞主进程了吗？

[Profile-20210512T160124.zip](https://github.com/lanten/electron-antd/files/6464524/Profile-20210512T160124.zip)

这是性能分析记录，能否帮忙看下

**Comment by lanten** [comment]
一会儿我搞个demo调测一下，如有进展，我会给你反馈

**Comment by linvva** [comment]
http://scrm.vipcall.net:11025/file/server/scrm-update/%E8%BD%AF%E5%8A%9B%E4%BA%91%20Setup%200.5.4.exe

好像也不止网络请求时，我使用的函数式组件，每次`setState`都掉帧，这是我们的客户端，如果有需要的话您可以下载后 `Ctrl` + `Shift` + `i` 进行调试，使用账号 `liuya` 密码 `123456`，如果需要的话我可以提供源码，并支付一定费用，感谢

**Comment by lanten** [comment]
经过调测，我可以确定这不是网络请求的问题。

我用的是mac ，所以你提供的demo我没法运行，我想你这种现象很可能是编码不规范导致的，函数式组件在每一次重渲染都会执行函数本身（相当于render ），这时候函数体内存在多少计算，每次 `setState` 就会消耗多少的算力，建议针对实际情况进行优化，比如将只需要执行一次的计算迁移至副作用函数: `React.useEffect(() => { }, [])`，使用 `React.memo()`, 优化算法等。
