### ISSUE TITLE
启用contextIsolation会导致报错

### ISSUE THREAD

**Issue by fengbujue2022** [lanten/electron-antd#41]
hi lanten 
https://github.com/lanten/electron-antd/blob/7581f0a8ee7c3787fcbe7a208ae3124344cb5f76/app/core/tools/consts.ts#L32
改为true后 报错如下
`
Uncaught ReferenceError: global is not defined
    at jsonp chunk loading:78
    at renderer.js:72447
    at startup:8
`

**Comment by fengbujue2022** [comment]
找到一个 [#issue](https://github.com/electron/electron/issues/11608#issuecomment-358017327)，似乎是因为有引用node环境的代码，不太熟悉webpack ...不知道哪儿用了

**Comment by lanten** [comment]
这个设为 `true` 后 `remote` 模块的 `getGlobal` 就没法用了

相关代码：
https://github.com/lanten/electron-antd/blob/7581f0a8ee7c3787fcbe7a208ae3124344cb5f76/app/core/renderer.init.ts#L1-L7
https://github.com/lanten/electron-antd/blob/7581f0a8ee7c3787fcbe7a208ae3124344cb5f76/app/core/main.init.ts#L1-L13

webpack:
https://github.com/lanten/electron-antd/blob/7581f0a8ee7c3787fcbe7a208ae3124344cb5f76/build/webpack.config.base.ts#L37-L39

这个玩意儿主要目的是为了将主进程内存中的变量共享给渲染进程

请问你为什么要禁用它？

**Comment by fengbujue2022** [comment]
实际上我已经在我的项目里移除了这些代码  但仍遇到了
``` javascript
Uncaught ReferenceError: require is not defined
    at Object.url (external "url":1)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Object../node_modules/webpack-dev-server/client/utils/createSocketUrl.js (createSocketUrl.js:4)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Object../node_modules/webpack-dev-server/client/index.js?http://localhost (index.js?ade4:20)
    at __webpack_require__ (bootstrap:24)
    at startup:4
    at startup:8
```

启用原因： 隔离上下文会使程序更安全？而且在electron 12是默认启用 [doc](https://github.com/electron/electron/blob/main/docs/tutorial/context-isolation.md)

**Comment by lanten** [comment]
可能的原因，尝试一下移除此文件及相关引用：

https://github.com/lanten/electron-antd/blob/7581f0a8ee7c3787fcbe7a208ae3124344cb5f76/app/core/tools/native-require.ts

**Comment by fengbujue2022** [comment]
谢谢作者回复~
https://gist.github.com/msafi/d1b8571aa921feaaa0f893ab24bb727b#file-electron-webpack-require-is-not-defined-md
更改了webpack.config.renderer 的 target `electron-renderer` to `web` 解决了问题
