### ISSUE TITLE
窗口的最大化最小化的事件没有被触发

### ISSUE THREAD

**Issue by immortalt** [lanten/electron-antd#43]
文件路径：app/src/components/app-titlebar/app-titlebar.tsx
关键位置：
```
    this.currentWindow.on("maximize", this.onMaximize);
    this.currentWindow.on("unmaximize", this.onUnmaximize);

    ......

  onMaximize = (): void => {
    this.setState({ maximized: true });
  };

  onUnmaximize = (): void => {
    this.setState({ maximized: false });
  };
```
操作系统：Ubuntu 20.04 LTS  
Node版本：v14.16.1  
Electron版本：12.0.2  
问题：  
本来窗口最大化后最大化按钮应该也会因此事件变为取消最大化的按钮，但是因为事件没有触发所以最大化按钮最大化后没有变化。  
临时不靠谱的修复方案：取消事件机制，每次点击后主动setState修改状态。
```
  onClick={() => {
            this.currentWindow.unmaximize();
            this.setState({ maximized: false });
          }}
 ......
  onClick={() => {
            this.currentWindow.maximize();
            this.setState({ maximized: true });
          }}
```
刚打开这个项目，不清楚怎么回事，如果作者有空烦请看看。  
如果能事件触发那必然更优雅和靠谱，希望作者能找到事件机制失效的原因修复它。  
实在不行再考虑我这种机制，也许也得加个最大化是否成功的检测再决定是否setState。

**Comment by immortalt** [comment]
问题的根源大概是这样：
```
  componentDidMount(): void {
    window.addEventListener('router-update', this.onRouterUpdate)
    console.log('this.currentWindow', this.currentWindow)
    this.currentWindow.on('maximize', this.onMaximize)
    this.currentWindow.on('unmaximize', this.onUnmaximize)
  }
```
在componentDidMount声明的this.currentWindow，在componentDidMount执行时获取到的窗口是不正确的，有可能是太早了，所以没有成功监听窗口的最大化相关事件。

**Comment by lanten** [comment]
@Immortalt 恩，这个问题之前也有看到过，不过最近比较忙可能没时间搞，如果年有兴趣的话，欢迎PR！

**Comment by lanten** [comment]
@Immortalt 
这是 electron 的一个已知 bug，并延续到版本16：https://github.com/electron/electron/issues/28699 ，直到5天前这个PR被合并。

所以我觉得还是不更改代码比较好，等17版本正式发布更新一下依赖即可。
