### ISSUE TITLE
想请问一下有计划集成主题功能吗（明亮和暗黑两种即可）

### ISSUE THREAD

**Issue by chanceyliu** [lanten/electron-antd#50]

**Comment by lanten** [comment]
有的，我正在进行webpack切换至vite重构工作，届时将支持系统主题模式，时间不确定，最快两到三周吧。

此外我还对现有架构上一些设计不合理的地方及应用安全性方面进行了修正和优化，如弃用remote模块、弃用redux等，所以重构后的版本与现有版本存在很大差异，如果业务代码量大的话，迁移成本可能比较高。

**Comment by chanceyliu** [comment]
好的，感谢
