### ISSUE TITLE
 报错：babel-node: command not found

### ISSUE THREAD

**Issue by gailufeng** [lanten/electron-antd#6]
报错：babel-node: command not found， 

执行 npm install babel 也不起作用

**Comment by lanten** [comment]
我尝试拉取一个新的储存库，然后执行 `npm install` 和 `npm run dev`, 并没有发现问题。

首先你要先进入到项目目录并执行 `npm install`，
然后再执行 `npm run dev`。

你也可以尝试使用 `yarn`:
```
npm i -g yang && yarn
```
