### ISSUE TITLE
您好，我刚学，请教一下基础问题，如何打包成EXE?

### ISSUE THREAD

**Issue by ffywhxf** [lanten/electron-antd#8]
production
production F:\xiangmu\electron-antd-master\src
Build completed in 10.353s

编译完成!
Packaging app for platform win32 x64 using electron v4.2.4

卡在这好久都没反应。。。

**Comment by lanten** [comment]
打包的时候需要下载一个库
国内的网络不好你可以多等一会儿
或者挂ss走终端代理
或者配置国内镜像 ： [官方文档](https://electronjs.org/docs/tutorial/installation#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%95%9C%E5%83%8F%E5%92%8C%E7%BC%93%E5%AD%98)

**Comment by ffywhxf** [comment]
感谢前辈，我用npm、cnpm、pnpm、yarn、tyarn全试了一遍，终于可以了。
但又有一个问题，直接打包出来有200M这么大（还没改动过任何代码）
是`package.config.js`里的`ignore`要改一下吗？
